### ISSUE TITLE
feat: Product title in product model.

### ISSUE THREAD

**Issue by hastebrot** [hastebrot/2024-ecommerce-platform#15]
| original estimate | estimate | actual effort | remaining effort |
|--|--|--|--|
| 3h | 4h | 4h30h | 0h |

not the cleanest story I've written, but I know what to do.

write clients in `shop-ui`, `api-gateway`, and `catalog` services. write zod-typed models for the endpoints, requests and responses, and messages. implement write product then read product to key-value store which is straight-forward to test. then read all products from the store and pass it to the UI into the page endpoint and decent to `ProductList` and `ProductTile` components.

**acceptance criteria:**
- we have `productTitle` field in `Product` model
- we can read and write a `Product` using `api-gateway` and the data is persisted
- we can read `Product`s from `shop-ui` service
- products are listed as product tiles on `product-listing` page
- product title is displayed in product tile

**out of scope:**
- endpoint to delete products

**testing instructions:**

```sh
❯ curlie POST "http://localhost:8080/api/catalog/read-products" --data "{}" "x-workspace: test"
HTTP/1.1 200 OK
content-type: application/json;charset=utf-8
vary: Accept-Encoding
content-length: 509
date: Fri, 26 Jul 2024 22:23:54 GMT

{
    "ok": true,
    "result": {
        "products": [
            {
                "id": "1",
                "productTitle": "product title",
                "createdDate": "2024-07-26T22:23:05.439Z",
                "lastModifiedDate": "2024-07-26T22:23:05.439Z"
            },
            {
                "id": "2",
                "productTitle": "other product title",
                "createdDate": "2024-07-26T22:23:05.442Z",
                "lastModifiedDate": "2024-07-26T22:23:05.442Z"
            }
        ]
    },
    "count": {
        "products": 2
    },
    "time": "3ms 778µs",
    "size": "466 B"
}
```

**task breakdown:**
- [x] in `__tests__`: create `api/product.test.ts`. add a `Deno.test()` which makes a `writeProduct` and `readProduct` request to a new endpoint in `api-gateway`. model should be `type Product { productTitle: string; }`. [1h]
- [x] in `catalog`: implement `ProductStoreClient.writeProduct()` and `readProduct()` which reads and writes products to a database. write zod models for `ProductStoreClient`, requests and responses, and the product model. in `api-gateway` pass requests to `catalog` service. [1h]
- [x] in `api-gateway`: implement `CatalogServiceClient.readProducts()` for `http://localhost:8080/api/catalog/read-products`. [20m]
- [x] in `catalog`: implement `ProductStoreClient.readProducts()` for `http://localhost:8081/catalog/read-products`. [20m]
- [x] in `shop-ui`: implement `CatalogClient.readProducts()` used by `http://localhost:8082/ui/product-listing-page`. [20m]
- [x] in `shop-ui`: use `CatalogClient` to read products into `product-listing-page`. in `__tests__` write `Deno.test()` for `ui/productListingPage.test.ts`. [30m]
- [x] create pull request, review, address review feedback, merge. [30m]

**technical details:**
- `Deno.Kv` can be used to store the `Product` model data into a key-value store, i.e. a SQLite file will be created in the `domains/shop/services/catalog` directory.
- we can use `Deno.addSignalListener("SIGINT", handler)` and `addEventListener("unload", handler)` to dispose resources, i.e. types `Deno.HttpServer` and `Deno.Kv`, which provide `http[Symbol.asyncDispose]()` and `kv[Symbol.dispose]()`.
- in `catalog` service we need a `ProductStoreClient`, in `api-gateway` service we need a `CatalogServiceClient`, and in `shop-ui` we need a `CatalogClient`.
- the `kv` keys for products should be prefixed with `["workspace", ctx.workspace, ...]`.
