### ISSUE TITLE
feat: Category path and attribute list in product model.

### ISSUE THREAD

**Issue by hastebrot** [hastebrot/2024-ecommerce-platform#16]
| original estimate | estimate | actual effort | remaining effort |
|--|--|--|--|
| 3h | 6h30m | 8h | 0h  |

**acceptance criteria:**
- we have a product model with category path and attribute list fields
- we can navigate to a category and filter by attributes

**testing instructions:**

**task breakdown:**
- [x] catalog, api-gateway: extend product model with category path and attribute list fields [2h]
- [x] tests: add test case for product-listing page with category and attributes URL params [2h]
- [x] tests: update demo fixtures for new product model [30m]
- [x] shop-ui: write client to fetch read-products endpoint, put the data into product tiles component [1h]
- [x] shop-ui: put product data into display options component as results count [1h]

**technical details:**
- `categoryPath` should be an array, when we query a category we'll look for one array item. `attributeList` should also be an array, on query we'll look for all attributes unless the array is empty
- brute-force filtering all products should be fine for the initial code.

```ts
export const Product = Zod.object("Product", {
  // ...
  categoryPath: z.array(z.lazy(() => Category)),
  attributeList: z.array(z.lazy(() => Attribute)),
});

export const Category = Zod.object("Category", {
  id: z.string(),
  category: z.string(),
});

export const Attribute = Zod.object("Attribute", {
  id: z.string(),
  attribute: z.string(),
});
```

```ts
export const ReadProductsRequest = Zod.object("ReadProductsRequest", {
  category: z.nullable(Category.shape["id"]).optional(),
  attributes: z.array(Attribute.shape["id"]).optional(),
});
```
