### ISSUE TITLE
feat: Attribute facets in product result.

### ISSUE THREAD

**Issue by hastebrot** [hastebrot/2024-ecommerce-platform#25]
**acceptance criteria:**
- we have a list of attributes in the "Eigenschaften" facet group
- we can use the attribute facet items to filter products in product listing by attribute
- attributes are listed alphabetically

**testing instructions:**

**task breakdown:**
- [ ] in `catalog`, collect attribute list in product result [2h]
- [ ] in `shop-ui`, list attributes in facet group [1h]
- [ ] in `shop-ui`, filter products by attribute [1h]

**technical details:**
- there is a facet group for "Eigenschaften" which lists all attributes.
- each attribute is selectable, i.e. each item has a checkbox.
- attributes are stored in the product model in `attributeList` field.
