### ISSUE TITLE
feat: Category breadcrumbs in product result.

### ISSUE THREAD

**Issue by hastebrot** [hastebrot/2024-ecommerce-platform#30]
| original estimate | estimate | actual effort | remaining effort |
|--|--|--|--|
| 2h | 2h30m | 2h30m  | 0h  |

**acceptance criteria:**
- we use breadcrumbs in product-listing to show the current category path
- the breadcrumbs have `<a>` links the reference category id for navigation

**testing instructions:**

**task breakdown:**
- [x] catalog, api-gateway: add ~~`category` and~~ `categoryPath` to `ReadProductsResponse`. update `ProductStoreClient.readProducts()` to pick `categoryPath`. [1h]
- [x] shop-ui: for product-listing pass `categoryPath` to `<Breadcrumbs>`. add `link` to `<BreadcrumbsLink>`. [1h]
- [x] tests: write test case with product fixtures that have categories on the same category path, and separate categories with different category paths. assert it transforms category path into `<Breadcrumbs>`. [30m]

**technical details:**
- the `category` URL param determines which category path is resolved. the category path is included in the `ReadProductsResponse`.
- since `Product` contains `categoryPath` we can just pick the category path of the first item in products and slice the array to end with the current category. however, the `product` array can be empty, hence we need to already determine the `categoryPath` while filtering the products.
- prefer `<a>` browser navigation over HTMX swapping and push URL for now.
