### ISSUE TITLE
feat: Pagination for product listing.

### ISSUE THREAD

**Issue by hastebrot** [hastebrot/2024-ecommerce-platform#34]
**acceptance criteria:**
- in product listing we have a pagination component
- current page element and items per page select allow interactions
- the number of pages and the navigation between pages works

**testing instructions:**

**task breakdown:**
- [ ] in `shop-ui`, create product listing pagination component [2h30m]
- [ ] in `catalog`, add `pageNumber` and `itemsPerPage` fields to read products request, handle fields in endpoint [2h]
- [ ] in `shop-ui`, handle navigation, total number of pages, current page, and changes to the items per page select [2h]

**technical details:**
- for pagination we need products per page and current page number
- product listing has a select component for number of products per page
- we need to implement the pagination component with the design
