### ISSUE TITLE
feat: Category tree facets in product result.

### ISSUE THREAD

**Issue by hastebrot** [hastebrot/2024-ecommerce-platform#36]
**acceptance criteria:**
- we have first level of categories of all products in the "Kategorien" facet group
- we can navigate between categories, i.e. it filters the project of the category
- category title and number of products in heading are updated
- categories are sorted alphabetically, except "Obst & Gemüse" which is on first position

**testing instructions:**

**task breakdown:**
- [ ] in `catalog`, iterate over all products and collect a list of categories, update models and endpoint messages [2h]
- [ ] in `shop-ui`, use `categories` list and fill the facet group for categories [1h]
- [ ] in `shop-ui`, add links to navigate between categories and show active category [30m]
- [ ] in `shop-ui`, update the heading for current category and number of products [30m]

**technical details:**
- product model contains a `categoryPath` field. since the list of categories is associated with the product result, we should include them in the endpoint for product results for now.
- we just iteration over all products and collect the list of all categories
